[package]
name = "eternal_emperor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiled = "0.10.1"
tiled-json-rs = "0.1.0"
sdl2 = "0.35.2"
imgui-rs = "1.47.0"